# Site settings
title: Duo Film
email: hello@duo-film.com
url: https://duo-film.com
description: "Duo Film"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 336e7b #80B3FF
  secondary: 95a5a6 #FD6E8A
  secondary-dark: 95a5a6 #A2122F

# Footer settings
footer:
  copyright: Casanova Tapia

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/casanovatapia
  - title: twitter
    url: http://twitter.com/karlelandler

# Build settings
markdown: kramdown
permalink: pretty

# For deploying on Heroku
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
